// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqdwcsglukvmvarghviz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxZHdjc2dsdWt2bXZhcmdodml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NjI4MzcsImV4cCI6MjA2NTAzODgzN30.nNxb3FOSudKhdnfZJG3H8Jbj0gbp_xoap1tH4zxypX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);